### ISSUE TITLE
Difficulty Bug

### ISSUE THREAD

**Issue by jenice11** [GothicIII/DJMaxRespectV-Randomizer#1]
Sometimes the randomized song's difficulty is not within range selected. 
Also the range at the bottom will be incorrect as well

![image](https://user-images.githubusercontent.com/38397984/173234105-20775070-cb29-4778-90fc-8110cfd621b4.png)

P.S: I tried with method 1, method 2 and method 3 as well

**Comment by GothicIII** [comment]
Does the error occur in that screenshot? I don't see any problems except the slider is a bit off. 

Your selected range is 8* to 12* with all difficulties. Fly Away 4k HD 10* is inside that boundary, so it works in that case.

I have a fallback code for cases where you select e.g. 1* SC diffciculty. In that case the boundaries are expanded until a song matches that sc difficulty so no infinite loop occurs.

EDIT: I can replicate the problem now. That's a logic problem. I'll fix that.

**Comment by GothicIII** [comment]
Alright. I rewrote some parts and replaced the random logic.
Now checkboxes will be disabled when invalid filter options are set. e.g. It won't be possible to select 1* sc difficulty mode.

Please check out the Beta.

**Comment by jenice11** [comment]
Checked out the beta, 
~~sometimes the music selected in game will be off by a song in the list, 
so i checked again for initial release, its also the same. But most of the time its fine. I did not pay attention to the song name in game previously~~
Nevermind I figured it must have been the dlc incorrectly ticked, works perfectly now
